import 'package:flow_reading/domain/models/app_failure.dart';

typedef AiJsonMap = Map<String, Object?>;

/// Describes the output shape requested from an AI provider.
sealed class AiResponseFormat {
  const AiResponseFormat();
}

/// Requests ordinary provider text output.
final class AiTextResponseFormat extends AiResponseFormat {
  const AiTextResponseFormat();
}

/// Requests JSON constrained by a provider-independent schema.
final class AiJsonResponseFormat extends AiResponseFormat {
  AiJsonResponseFormat({required this.name, required AiJsonMap schema})
    : schema = Map.unmodifiable(schema) {
    if (name.trim().isEmpty) {
      throw ArgumentError.value(name, 'name', 'Must not be empty');
    }
  }

  final String name;
  final AiJsonMap schema;
}

/// Provider-neutral input for one model generation.
final class AiProviderRequest {
  AiProviderRequest({
    required this.model,
    required this.instructions,
    required this.input,
    this.responseFormat = const AiTextResponseFormat(),
    this.maxOutputTokens,
  }) {
    if (model.trim().isEmpty) {
      throw ArgumentError.value(model, 'model', 'Must not be empty');
    }
    if (instructions.trim().isEmpty) {
      throw ArgumentError.value(
        instructions,
        'instructions',
        'Must not be empty',
      );
    }
    if (input.trim().isEmpty) {
      throw ArgumentError.value(input, 'input', 'Must not be empty');
    }
    if (maxOutputTokens case final value? when value <= 0) {
      throw ArgumentError.value(value, 'maxOutputTokens', 'Must be positive');
    }
  }

  final String model;
  final String instructions;
  final String input;
  final AiResponseFormat responseFormat;
  final int? maxOutputTokens;
}

/// A completed provider response and the implementation that produced it.
final class AiCompletion {
  AiCompletion({
    required this.text,
    required this.providerId,
    required this.model,
  }) {
    if (providerId.trim().isEmpty) {
      throw ArgumentError.value(providerId, 'providerId', 'Must not be empty');
    }
    if (model.trim().isEmpty) {
      throw ArgumentError.value(model, 'model', 'Must not be empty');
    }
  }

  final String text;
  final String providerId;
  final String model;
}

/// One provider-neutral event from a streaming generation.
sealed class AiStreamEvent {
  const AiStreamEvent();
}

/// Incremental text generated by a provider.
final class AiTextDelta extends AiStreamEvent {
  const AiTextDelta(this.text);

  final String text;
}

/// Terminal event containing the completed response.
final class AiStreamCompleted extends AiStreamEvent {
  const AiStreamCompleted(this.completion);

  final AiCompletion completion;
}

/// Terminal event containing a sanitized application failure.
final class AiStreamFailed extends AiStreamEvent {
  const AiStreamFailed(this.failure);

  final AppFailure failure;
}

/// Terminal event emitted after user-requested cancellation.
final class AiStreamCancelled extends AiStreamEvent {
  const AiStreamCancelled();
}

/// Controls and observes one streaming provider request.
abstract interface class AiStreamOperation {
  Stream<AiStreamEvent> get events;

  /// Cancels the active request and releases its provider resources.
  Future<void> cancel();
}
